package com.fc.v2.iotmanage.mapper;

import com.fc.v2.iotmanage.model.respone.SmokeInfo;
import com.fc.v2.iotmanage.model.respone.SmokeInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmokeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoke_info
     *
     * @mbg.generated
     */
    long countByExample(SmokeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoke_info
     *
     * @mbg.generated
     */
    int deleteByExample(SmokeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoke_info
     *
     * @mbg.generated
     */
    int insert(SmokeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoke_info
     *
     * @mbg.generated
     */
    int insertSelective(SmokeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoke_info
     *
     * @mbg.generated
     */
    List<SmokeInfo> selectByExample(SmokeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoke_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SmokeInfo record, @Param("example") SmokeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smoke_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SmokeInfo record, @Param("example") SmokeInfoExample example);
}