package com.fc.v2.iotmanage.mapper;

import com.fc.v2.iotmanage.model.respone.SocketInfo;
import com.fc.v2.iotmanage.model.respone.SocketInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SocketInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    long countByExample(SocketInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    int deleteByExample(SocketInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    int insert(SocketInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    int insertSelective(SocketInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    List<SocketInfo> selectByExample(SocketInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SocketInfo record, @Param("example") SocketInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SocketInfo record, @Param("example") SocketInfoExample example);
}