package com.fc.v2.iotmanage.mapper;

import com.fc.v2.iotmanage.model.respone.SpaceInfo;
import com.fc.v2.iotmanage.model.respone.SpaceInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpaceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    long countByExample(SpaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    int deleteByExample(SpaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    int insert(SpaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    int insertSelective(SpaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    List<SpaceInfo> selectByExample(SpaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SpaceInfo record, @Param("example") SpaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SpaceInfo record, @Param("example") SpaceInfoExample example);
}