package com.fc.v2.iotmanage.mapper;

import com.fc.v2.iotmanage.model.respone.SwitchInfo;
import com.fc.v2.iotmanage.model.respone.SwitchInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SwitchInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    long countByExample(SwitchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    int deleteByExample(SwitchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    int insert(SwitchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    int insertSelective(SwitchInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    List<SwitchInfo> selectByExample(SwitchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SwitchInfo record, @Param("example") SwitchInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SwitchInfo record, @Param("example") SwitchInfoExample example);
}