package com.fc.v2.iotmanage.model.respone;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AirConditionInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public AirConditionInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAirconIdIsNull() {
            addCriterion("aircon_id is null");
            return (Criteria) this;
        }

        public Criteria andAirconIdIsNotNull() {
            addCriterion("aircon_id is not null");
            return (Criteria) this;
        }

        public Criteria andAirconIdEqualTo(Integer value) {
            addCriterion("aircon_id =", value, "airconId");
            return (Criteria) this;
        }

        public Criteria andAirconIdNotEqualTo(Integer value) {
            addCriterion("aircon_id <>", value, "airconId");
            return (Criteria) this;
        }

        public Criteria andAirconIdGreaterThan(Integer value) {
            addCriterion("aircon_id >", value, "airconId");
            return (Criteria) this;
        }

        public Criteria andAirconIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("aircon_id >=", value, "airconId");
            return (Criteria) this;
        }

        public Criteria andAirconIdLessThan(Integer value) {
            addCriterion("aircon_id <", value, "airconId");
            return (Criteria) this;
        }

        public Criteria andAirconIdLessThanOrEqualTo(Integer value) {
            addCriterion("aircon_id <=", value, "airconId");
            return (Criteria) this;
        }

        public Criteria andAirconIdIn(List<Integer> values) {
            addCriterion("aircon_id in", values, "airconId");
            return (Criteria) this;
        }

        public Criteria andAirconIdNotIn(List<Integer> values) {
            addCriterion("aircon_id not in", values, "airconId");
            return (Criteria) this;
        }

        public Criteria andAirconIdBetween(Integer value1, Integer value2) {
            addCriterion("aircon_id between", value1, value2, "airconId");
            return (Criteria) this;
        }

        public Criteria andAirconIdNotBetween(Integer value1, Integer value2) {
            addCriterion("aircon_id not between", value1, value2, "airconId");
            return (Criteria) this;
        }

        public Criteria andAirconNameIsNull() {
            addCriterion("aircon_name is null");
            return (Criteria) this;
        }

        public Criteria andAirconNameIsNotNull() {
            addCriterion("aircon_name is not null");
            return (Criteria) this;
        }

        public Criteria andAirconNameEqualTo(String value) {
            addCriterion("aircon_name =", value, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameNotEqualTo(String value) {
            addCriterion("aircon_name <>", value, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameGreaterThan(String value) {
            addCriterion("aircon_name >", value, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameGreaterThanOrEqualTo(String value) {
            addCriterion("aircon_name >=", value, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameLessThan(String value) {
            addCriterion("aircon_name <", value, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameLessThanOrEqualTo(String value) {
            addCriterion("aircon_name <=", value, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameLike(String value) {
            addCriterion("aircon_name like", value, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameNotLike(String value) {
            addCriterion("aircon_name not like", value, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameIn(List<String> values) {
            addCriterion("aircon_name in", values, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameNotIn(List<String> values) {
            addCriterion("aircon_name not in", values, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameBetween(String value1, String value2) {
            addCriterion("aircon_name between", value1, value2, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirconNameNotBetween(String value1, String value2) {
            addCriterion("aircon_name not between", value1, value2, "airconName");
            return (Criteria) this;
        }

        public Criteria andAirTempIsNull() {
            addCriterion("air_temp is null");
            return (Criteria) this;
        }

        public Criteria andAirTempIsNotNull() {
            addCriterion("air_temp is not null");
            return (Criteria) this;
        }

        public Criteria andAirTempEqualTo(String value) {
            addCriterion("air_temp =", value, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempNotEqualTo(String value) {
            addCriterion("air_temp <>", value, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempGreaterThan(String value) {
            addCriterion("air_temp >", value, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempGreaterThanOrEqualTo(String value) {
            addCriterion("air_temp >=", value, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempLessThan(String value) {
            addCriterion("air_temp <", value, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempLessThanOrEqualTo(String value) {
            addCriterion("air_temp <=", value, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempLike(String value) {
            addCriterion("air_temp like", value, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempNotLike(String value) {
            addCriterion("air_temp not like", value, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempIn(List<String> values) {
            addCriterion("air_temp in", values, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempNotIn(List<String> values) {
            addCriterion("air_temp not in", values, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempBetween(String value1, String value2) {
            addCriterion("air_temp between", value1, value2, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirTempNotBetween(String value1, String value2) {
            addCriterion("air_temp not between", value1, value2, "airTemp");
            return (Criteria) this;
        }

        public Criteria andAirStatusIsNull() {
            addCriterion("air_status is null");
            return (Criteria) this;
        }

        public Criteria andAirStatusIsNotNull() {
            addCriterion("air_status is not null");
            return (Criteria) this;
        }

        public Criteria andAirStatusEqualTo(String value) {
            addCriterion("air_status =", value, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusNotEqualTo(String value) {
            addCriterion("air_status <>", value, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusGreaterThan(String value) {
            addCriterion("air_status >", value, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusGreaterThanOrEqualTo(String value) {
            addCriterion("air_status >=", value, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusLessThan(String value) {
            addCriterion("air_status <", value, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusLessThanOrEqualTo(String value) {
            addCriterion("air_status <=", value, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusLike(String value) {
            addCriterion("air_status like", value, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusNotLike(String value) {
            addCriterion("air_status not like", value, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusIn(List<String> values) {
            addCriterion("air_status in", values, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusNotIn(List<String> values) {
            addCriterion("air_status not in", values, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusBetween(String value1, String value2) {
            addCriterion("air_status between", value1, value2, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirStatusNotBetween(String value1, String value2) {
            addCriterion("air_status not between", value1, value2, "airStatus");
            return (Criteria) this;
        }

        public Criteria andAirModeIsNull() {
            addCriterion("air_mode is null");
            return (Criteria) this;
        }

        public Criteria andAirModeIsNotNull() {
            addCriterion("air_mode is not null");
            return (Criteria) this;
        }

        public Criteria andAirModeEqualTo(String value) {
            addCriterion("air_mode =", value, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeNotEqualTo(String value) {
            addCriterion("air_mode <>", value, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeGreaterThan(String value) {
            addCriterion("air_mode >", value, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeGreaterThanOrEqualTo(String value) {
            addCriterion("air_mode >=", value, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeLessThan(String value) {
            addCriterion("air_mode <", value, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeLessThanOrEqualTo(String value) {
            addCriterion("air_mode <=", value, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeLike(String value) {
            addCriterion("air_mode like", value, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeNotLike(String value) {
            addCriterion("air_mode not like", value, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeIn(List<String> values) {
            addCriterion("air_mode in", values, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeNotIn(List<String> values) {
            addCriterion("air_mode not in", values, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeBetween(String value1, String value2) {
            addCriterion("air_mode between", value1, value2, "airMode");
            return (Criteria) this;
        }

        public Criteria andAirModeNotBetween(String value1, String value2) {
            addCriterion("air_mode not between", value1, value2, "airMode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Integer value) {
            addCriterion("room_id =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Integer value) {
            addCriterion("room_id <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Integer value) {
            addCriterion("room_id >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_id >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Integer value) {
            addCriterion("room_id <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("room_id <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Integer> values) {
            addCriterion("room_id in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Integer> values) {
            addCriterion("room_id not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table air_condition_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table air_condition_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}