package com.fc.v2.iotmanage.model.respone;

import java.io.Serializable;
import java.util.Date;

public class EnvInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_info.env_id
     *
     * @mbg.generated
     */
    private Integer envId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_info.env_name
     *
     * @mbg.generated
     */
    private String envName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_info.env_temp
     *
     * @mbg.generated
     */
    private String envTemp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_info.env_hum
     *
     * @mbg.generated
     */
    private String envHum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_info.env_ele
     *
     * @mbg.generated
     */
    private String envEle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column env_info.room_id
     *
     * @mbg.generated
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table env_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_info.id
     *
     * @return the value of env_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_info.id
     *
     * @param id the value for env_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_info.env_id
     *
     * @return the value of env_info.env_id
     *
     * @mbg.generated
     */
    public Integer getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_info.env_id
     *
     * @param envId the value for env_info.env_id
     *
     * @mbg.generated
     */
    public void setEnvId(Integer envId) {
        this.envId = envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_info.env_name
     *
     * @return the value of env_info.env_name
     *
     * @mbg.generated
     */
    public String getEnvName() {
        return envName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_info.env_name
     *
     * @param envName the value for env_info.env_name
     *
     * @mbg.generated
     */
    public void setEnvName(String envName) {
        this.envName = envName == null ? null : envName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_info.env_temp
     *
     * @return the value of env_info.env_temp
     *
     * @mbg.generated
     */
    public String getEnvTemp() {
        return envTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_info.env_temp
     *
     * @param envTemp the value for env_info.env_temp
     *
     * @mbg.generated
     */
    public void setEnvTemp(String envTemp) {
        this.envTemp = envTemp == null ? null : envTemp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_info.env_hum
     *
     * @return the value of env_info.env_hum
     *
     * @mbg.generated
     */
    public String getEnvHum() {
        return envHum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_info.env_hum
     *
     * @param envHum the value for env_info.env_hum
     *
     * @mbg.generated
     */
    public void setEnvHum(String envHum) {
        this.envHum = envHum == null ? null : envHum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_info.env_ele
     *
     * @return the value of env_info.env_ele
     *
     * @mbg.generated
     */
    public String getEnvEle() {
        return envEle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_info.env_ele
     *
     * @param envEle the value for env_info.env_ele
     *
     * @mbg.generated
     */
    public void setEnvEle(String envEle) {
        this.envEle = envEle == null ? null : envEle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_info.create_time
     *
     * @return the value of env_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_info.create_time
     *
     * @param createTime the value for env_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column env_info.room_id
     *
     * @return the value of env_info.room_id
     *
     * @mbg.generated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column env_info.room_id
     *
     * @param roomId the value for env_info.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }
}