package com.fc.v2.iotmanage.model.respone;

import java.io.Serializable;

public class RoomInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_id
     *
     * @mbg.generated
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_id_v
     *
     * @mbg.generated
     */
    private String roomIdV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_name
     *
     * @mbg.generated
     */
    private String roomName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.switch_status
     *
     * @mbg.generated
     */
    private String switchStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.socket10_1_status
     *
     * @mbg.generated
     */
    private String socket101Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.socket10_2_status
     *
     * @mbg.generated
     */
    private String socket102Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.socket16_status
     *
     * @mbg.generated
     */
    private String socket16Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.aircondt_status
     *
     * @mbg.generated
     */
    private String aircondtStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.space_id
     *
     * @mbg.generated
     */
    private Integer spaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.room_id
     *
     * @return the value of room_info.room_id
     *
     * @mbg.generated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.room_id
     *
     * @param roomId the value for room_info.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.room_id_v
     *
     * @return the value of room_info.room_id_v
     *
     * @mbg.generated
     */
    public String getRoomIdV() {
        return roomIdV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.room_id_v
     *
     * @param roomIdV the value for room_info.room_id_v
     *
     * @mbg.generated
     */
    public void setRoomIdV(String roomIdV) {
        this.roomIdV = roomIdV == null ? null : roomIdV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.room_name
     *
     * @return the value of room_info.room_name
     *
     * @mbg.generated
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.room_name
     *
     * @param roomName the value for room_info.room_name
     *
     * @mbg.generated
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName == null ? null : roomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.switch_status
     *
     * @return the value of room_info.switch_status
     *
     * @mbg.generated
     */
    public String getSwitchStatus() {
        return switchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.switch_status
     *
     * @param switchStatus the value for room_info.switch_status
     *
     * @mbg.generated
     */
    public void setSwitchStatus(String switchStatus) {
        this.switchStatus = switchStatus == null ? null : switchStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.socket10_1_status
     *
     * @return the value of room_info.socket10_1_status
     *
     * @mbg.generated
     */
    public String getSocket101Status() {
        return socket101Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.socket10_1_status
     *
     * @param socket101Status the value for room_info.socket10_1_status
     *
     * @mbg.generated
     */
    public void setSocket101Status(String socket101Status) {
        this.socket101Status = socket101Status == null ? null : socket101Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.socket10_2_status
     *
     * @return the value of room_info.socket10_2_status
     *
     * @mbg.generated
     */
    public String getSocket102Status() {
        return socket102Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.socket10_2_status
     *
     * @param socket102Status the value for room_info.socket10_2_status
     *
     * @mbg.generated
     */
    public void setSocket102Status(String socket102Status) {
        this.socket102Status = socket102Status == null ? null : socket102Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.socket16_status
     *
     * @return the value of room_info.socket16_status
     *
     * @mbg.generated
     */
    public String getSocket16Status() {
        return socket16Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.socket16_status
     *
     * @param socket16Status the value for room_info.socket16_status
     *
     * @mbg.generated
     */
    public void setSocket16Status(String socket16Status) {
        this.socket16Status = socket16Status == null ? null : socket16Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.aircondt_status
     *
     * @return the value of room_info.aircondt_status
     *
     * @mbg.generated
     */
    public String getAircondtStatus() {
        return aircondtStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.aircondt_status
     *
     * @param aircondtStatus the value for room_info.aircondt_status
     *
     * @mbg.generated
     */
    public void setAircondtStatus(String aircondtStatus) {
        this.aircondtStatus = aircondtStatus == null ? null : aircondtStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.space_id
     *
     * @return the value of room_info.space_id
     *
     * @mbg.generated
     */
    public Integer getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.space_id
     *
     * @param spaceId the value for room_info.space_id
     *
     * @mbg.generated
     */
    public void setSpaceId(Integer spaceId) {
        this.spaceId = spaceId;
    }
}