package com.fc.v2.iotmanage.model.respone;

import java.util.ArrayList;
import java.util.List;

public class RoomInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public RoomInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Integer value) {
            addCriterion("room_id =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Integer value) {
            addCriterion("room_id <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Integer value) {
            addCriterion("room_id >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_id >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Integer value) {
            addCriterion("room_id <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("room_id <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Integer> values) {
            addCriterion("room_id in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Integer> values) {
            addCriterion("room_id not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdVIsNull() {
            addCriterion("room_id_v is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdVIsNotNull() {
            addCriterion("room_id_v is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdVEqualTo(String value) {
            addCriterion("room_id_v =", value, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVNotEqualTo(String value) {
            addCriterion("room_id_v <>", value, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVGreaterThan(String value) {
            addCriterion("room_id_v >", value, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVGreaterThanOrEqualTo(String value) {
            addCriterion("room_id_v >=", value, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVLessThan(String value) {
            addCriterion("room_id_v <", value, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVLessThanOrEqualTo(String value) {
            addCriterion("room_id_v <=", value, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVLike(String value) {
            addCriterion("room_id_v like", value, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVNotLike(String value) {
            addCriterion("room_id_v not like", value, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVIn(List<String> values) {
            addCriterion("room_id_v in", values, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVNotIn(List<String> values) {
            addCriterion("room_id_v not in", values, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVBetween(String value1, String value2) {
            addCriterion("room_id_v between", value1, value2, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomIdVNotBetween(String value1, String value2) {
            addCriterion("room_id_v not between", value1, value2, "roomIdV");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNull() {
            addCriterion("room_name is null");
            return (Criteria) this;
        }

        public Criteria andRoomNameIsNotNull() {
            addCriterion("room_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoomNameEqualTo(String value) {
            addCriterion("room_name =", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotEqualTo(String value) {
            addCriterion("room_name <>", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThan(String value) {
            addCriterion("room_name >", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("room_name >=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThan(String value) {
            addCriterion("room_name <", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLessThanOrEqualTo(String value) {
            addCriterion("room_name <=", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameLike(String value) {
            addCriterion("room_name like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotLike(String value) {
            addCriterion("room_name not like", value, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameIn(List<String> values) {
            addCriterion("room_name in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotIn(List<String> values) {
            addCriterion("room_name not in", values, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameBetween(String value1, String value2) {
            addCriterion("room_name between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andRoomNameNotBetween(String value1, String value2) {
            addCriterion("room_name not between", value1, value2, "roomName");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusIsNull() {
            addCriterion("switch_status is null");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusIsNotNull() {
            addCriterion("switch_status is not null");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusEqualTo(String value) {
            addCriterion("switch_status =", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusNotEqualTo(String value) {
            addCriterion("switch_status <>", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusGreaterThan(String value) {
            addCriterion("switch_status >", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusGreaterThanOrEqualTo(String value) {
            addCriterion("switch_status >=", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusLessThan(String value) {
            addCriterion("switch_status <", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusLessThanOrEqualTo(String value) {
            addCriterion("switch_status <=", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusLike(String value) {
            addCriterion("switch_status like", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusNotLike(String value) {
            addCriterion("switch_status not like", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusIn(List<String> values) {
            addCriterion("switch_status in", values, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusNotIn(List<String> values) {
            addCriterion("switch_status not in", values, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusBetween(String value1, String value2) {
            addCriterion("switch_status between", value1, value2, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusNotBetween(String value1, String value2) {
            addCriterion("switch_status not between", value1, value2, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusIsNull() {
            addCriterion("socket10_1_status is null");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusIsNotNull() {
            addCriterion("socket10_1_status is not null");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusEqualTo(String value) {
            addCriterion("socket10_1_status =", value, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusNotEqualTo(String value) {
            addCriterion("socket10_1_status <>", value, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusGreaterThan(String value) {
            addCriterion("socket10_1_status >", value, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusGreaterThanOrEqualTo(String value) {
            addCriterion("socket10_1_status >=", value, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusLessThan(String value) {
            addCriterion("socket10_1_status <", value, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusLessThanOrEqualTo(String value) {
            addCriterion("socket10_1_status <=", value, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusLike(String value) {
            addCriterion("socket10_1_status like", value, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusNotLike(String value) {
            addCriterion("socket10_1_status not like", value, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusIn(List<String> values) {
            addCriterion("socket10_1_status in", values, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusNotIn(List<String> values) {
            addCriterion("socket10_1_status not in", values, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusBetween(String value1, String value2) {
            addCriterion("socket10_1_status between", value1, value2, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket101StatusNotBetween(String value1, String value2) {
            addCriterion("socket10_1_status not between", value1, value2, "socket101Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusIsNull() {
            addCriterion("socket10_2_status is null");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusIsNotNull() {
            addCriterion("socket10_2_status is not null");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusEqualTo(String value) {
            addCriterion("socket10_2_status =", value, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusNotEqualTo(String value) {
            addCriterion("socket10_2_status <>", value, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusGreaterThan(String value) {
            addCriterion("socket10_2_status >", value, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusGreaterThanOrEqualTo(String value) {
            addCriterion("socket10_2_status >=", value, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusLessThan(String value) {
            addCriterion("socket10_2_status <", value, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusLessThanOrEqualTo(String value) {
            addCriterion("socket10_2_status <=", value, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusLike(String value) {
            addCriterion("socket10_2_status like", value, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusNotLike(String value) {
            addCriterion("socket10_2_status not like", value, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusIn(List<String> values) {
            addCriterion("socket10_2_status in", values, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusNotIn(List<String> values) {
            addCriterion("socket10_2_status not in", values, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusBetween(String value1, String value2) {
            addCriterion("socket10_2_status between", value1, value2, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket102StatusNotBetween(String value1, String value2) {
            addCriterion("socket10_2_status not between", value1, value2, "socket102Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusIsNull() {
            addCriterion("socket16_status is null");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusIsNotNull() {
            addCriterion("socket16_status is not null");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusEqualTo(String value) {
            addCriterion("socket16_status =", value, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusNotEqualTo(String value) {
            addCriterion("socket16_status <>", value, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusGreaterThan(String value) {
            addCriterion("socket16_status >", value, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusGreaterThanOrEqualTo(String value) {
            addCriterion("socket16_status >=", value, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusLessThan(String value) {
            addCriterion("socket16_status <", value, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusLessThanOrEqualTo(String value) {
            addCriterion("socket16_status <=", value, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusLike(String value) {
            addCriterion("socket16_status like", value, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusNotLike(String value) {
            addCriterion("socket16_status not like", value, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusIn(List<String> values) {
            addCriterion("socket16_status in", values, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusNotIn(List<String> values) {
            addCriterion("socket16_status not in", values, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusBetween(String value1, String value2) {
            addCriterion("socket16_status between", value1, value2, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andSocket16StatusNotBetween(String value1, String value2) {
            addCriterion("socket16_status not between", value1, value2, "socket16Status");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusIsNull() {
            addCriterion("aircondt_status is null");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusIsNotNull() {
            addCriterion("aircondt_status is not null");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusEqualTo(String value) {
            addCriterion("aircondt_status =", value, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusNotEqualTo(String value) {
            addCriterion("aircondt_status <>", value, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusGreaterThan(String value) {
            addCriterion("aircondt_status >", value, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusGreaterThanOrEqualTo(String value) {
            addCriterion("aircondt_status >=", value, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusLessThan(String value) {
            addCriterion("aircondt_status <", value, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusLessThanOrEqualTo(String value) {
            addCriterion("aircondt_status <=", value, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusLike(String value) {
            addCriterion("aircondt_status like", value, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusNotLike(String value) {
            addCriterion("aircondt_status not like", value, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusIn(List<String> values) {
            addCriterion("aircondt_status in", values, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusNotIn(List<String> values) {
            addCriterion("aircondt_status not in", values, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusBetween(String value1, String value2) {
            addCriterion("aircondt_status between", value1, value2, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andAircondtStatusNotBetween(String value1, String value2) {
            addCriterion("aircondt_status not between", value1, value2, "aircondtStatus");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Integer value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Integer value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Integer value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Integer> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Integer> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}