package com.fc.v2.iotmanage.model.respone;

import java.io.Serializable;
import java.util.Date;

public class ShopInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_id
     *
     * @mbg.generated
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_id_v
     *
     * @mbg.generated
     */
    private String shopIdV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.parent_id
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.parent_id_v
     *
     * @mbg.generated
     */
    private String parentIdV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_info.delete_flag
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_id
     *
     * @return the value of shop_info.shop_id
     *
     * @mbg.generated
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_id
     *
     * @param shopId the value for shop_info.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_id_v
     *
     * @return the value of shop_info.shop_id_v
     *
     * @mbg.generated
     */
    public String getShopIdV() {
        return shopIdV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_id_v
     *
     * @param shopIdV the value for shop_info.shop_id_v
     *
     * @mbg.generated
     */
    public void setShopIdV(String shopIdV) {
        this.shopIdV = shopIdV == null ? null : shopIdV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.parent_id
     *
     * @return the value of shop_info.parent_id
     *
     * @mbg.generated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.parent_id
     *
     * @param parentId the value for shop_info.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.parent_id_v
     *
     * @return the value of shop_info.parent_id_v
     *
     * @mbg.generated
     */
    public String getParentIdV() {
        return parentIdV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.parent_id_v
     *
     * @param parentIdV the value for shop_info.parent_id_v
     *
     * @mbg.generated
     */
    public void setParentIdV(String parentIdV) {
        this.parentIdV = parentIdV == null ? null : parentIdV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.shop_name
     *
     * @return the value of shop_info.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.shop_name
     *
     * @param shopName the value for shop_info.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.update_date
     *
     * @return the value of shop_info.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.update_date
     *
     * @param updateDate the value for shop_info.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_info.delete_flag
     *
     * @return the value of shop_info.delete_flag
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_info.delete_flag
     *
     * @param deleteFlag the value for shop_info.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}