package com.fc.v2.iotmanage.model.respone;

import java.io.Serializable;
import java.util.Date;

public class SmokeInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoke_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoke_info.smoke_id
     *
     * @mbg.generated
     */
    private Integer smokeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoke_info.smoke_name
     *
     * @mbg.generated
     */
    private String smokeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoke_info.smoke_status
     *
     * @mbg.generated
     */
    private String smokeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoke_info.smoke_ele
     *
     * @mbg.generated
     */
    private String smokeEle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoke_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smoke_info.room_id
     *
     * @mbg.generated
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smoke_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoke_info.id
     *
     * @return the value of smoke_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoke_info.id
     *
     * @param id the value for smoke_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoke_info.smoke_id
     *
     * @return the value of smoke_info.smoke_id
     *
     * @mbg.generated
     */
    public Integer getSmokeId() {
        return smokeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoke_info.smoke_id
     *
     * @param smokeId the value for smoke_info.smoke_id
     *
     * @mbg.generated
     */
    public void setSmokeId(Integer smokeId) {
        this.smokeId = smokeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoke_info.smoke_name
     *
     * @return the value of smoke_info.smoke_name
     *
     * @mbg.generated
     */
    public String getSmokeName() {
        return smokeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoke_info.smoke_name
     *
     * @param smokeName the value for smoke_info.smoke_name
     *
     * @mbg.generated
     */
    public void setSmokeName(String smokeName) {
        this.smokeName = smokeName == null ? null : smokeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoke_info.smoke_status
     *
     * @return the value of smoke_info.smoke_status
     *
     * @mbg.generated
     */
    public String getSmokeStatus() {
        return smokeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoke_info.smoke_status
     *
     * @param smokeStatus the value for smoke_info.smoke_status
     *
     * @mbg.generated
     */
    public void setSmokeStatus(String smokeStatus) {
        this.smokeStatus = smokeStatus == null ? null : smokeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoke_info.smoke_ele
     *
     * @return the value of smoke_info.smoke_ele
     *
     * @mbg.generated
     */
    public String getSmokeEle() {
        return smokeEle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoke_info.smoke_ele
     *
     * @param smokeEle the value for smoke_info.smoke_ele
     *
     * @mbg.generated
     */
    public void setSmokeEle(String smokeEle) {
        this.smokeEle = smokeEle == null ? null : smokeEle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoke_info.create_time
     *
     * @return the value of smoke_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoke_info.create_time
     *
     * @param createTime the value for smoke_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smoke_info.room_id
     *
     * @return the value of smoke_info.room_id
     *
     * @mbg.generated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smoke_info.room_id
     *
     * @param roomId the value for smoke_info.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }
}