package com.fc.v2.iotmanage.model.respone;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SocketInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public SocketInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSocketIdIsNull() {
            addCriterion("socket_id is null");
            return (Criteria) this;
        }

        public Criteria andSocketIdIsNotNull() {
            addCriterion("socket_id is not null");
            return (Criteria) this;
        }

        public Criteria andSocketIdEqualTo(Integer value) {
            addCriterion("socket_id =", value, "socketId");
            return (Criteria) this;
        }

        public Criteria andSocketIdNotEqualTo(Integer value) {
            addCriterion("socket_id <>", value, "socketId");
            return (Criteria) this;
        }

        public Criteria andSocketIdGreaterThan(Integer value) {
            addCriterion("socket_id >", value, "socketId");
            return (Criteria) this;
        }

        public Criteria andSocketIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("socket_id >=", value, "socketId");
            return (Criteria) this;
        }

        public Criteria andSocketIdLessThan(Integer value) {
            addCriterion("socket_id <", value, "socketId");
            return (Criteria) this;
        }

        public Criteria andSocketIdLessThanOrEqualTo(Integer value) {
            addCriterion("socket_id <=", value, "socketId");
            return (Criteria) this;
        }

        public Criteria andSocketIdIn(List<Integer> values) {
            addCriterion("socket_id in", values, "socketId");
            return (Criteria) this;
        }

        public Criteria andSocketIdNotIn(List<Integer> values) {
            addCriterion("socket_id not in", values, "socketId");
            return (Criteria) this;
        }

        public Criteria andSocketIdBetween(Integer value1, Integer value2) {
            addCriterion("socket_id between", value1, value2, "socketId");
            return (Criteria) this;
        }

        public Criteria andSocketIdNotBetween(Integer value1, Integer value2) {
            addCriterion("socket_id not between", value1, value2, "socketId");
            return (Criteria) this;
        }

        public Criteria andSocketNameIsNull() {
            addCriterion("socket_name is null");
            return (Criteria) this;
        }

        public Criteria andSocketNameIsNotNull() {
            addCriterion("socket_name is not null");
            return (Criteria) this;
        }

        public Criteria andSocketNameEqualTo(String value) {
            addCriterion("socket_name =", value, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameNotEqualTo(String value) {
            addCriterion("socket_name <>", value, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameGreaterThan(String value) {
            addCriterion("socket_name >", value, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameGreaterThanOrEqualTo(String value) {
            addCriterion("socket_name >=", value, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameLessThan(String value) {
            addCriterion("socket_name <", value, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameLessThanOrEqualTo(String value) {
            addCriterion("socket_name <=", value, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameLike(String value) {
            addCriterion("socket_name like", value, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameNotLike(String value) {
            addCriterion("socket_name not like", value, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameIn(List<String> values) {
            addCriterion("socket_name in", values, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameNotIn(List<String> values) {
            addCriterion("socket_name not in", values, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameBetween(String value1, String value2) {
            addCriterion("socket_name between", value1, value2, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketNameNotBetween(String value1, String value2) {
            addCriterion("socket_name not between", value1, value2, "socketName");
            return (Criteria) this;
        }

        public Criteria andSocketIIsNull() {
            addCriterion("socket_i is null");
            return (Criteria) this;
        }

        public Criteria andSocketIIsNotNull() {
            addCriterion("socket_i is not null");
            return (Criteria) this;
        }

        public Criteria andSocketIEqualTo(String value) {
            addCriterion("socket_i =", value, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketINotEqualTo(String value) {
            addCriterion("socket_i <>", value, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketIGreaterThan(String value) {
            addCriterion("socket_i >", value, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketIGreaterThanOrEqualTo(String value) {
            addCriterion("socket_i >=", value, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketILessThan(String value) {
            addCriterion("socket_i <", value, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketILessThanOrEqualTo(String value) {
            addCriterion("socket_i <=", value, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketILike(String value) {
            addCriterion("socket_i like", value, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketINotLike(String value) {
            addCriterion("socket_i not like", value, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketIIn(List<String> values) {
            addCriterion("socket_i in", values, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketINotIn(List<String> values) {
            addCriterion("socket_i not in", values, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketIBetween(String value1, String value2) {
            addCriterion("socket_i between", value1, value2, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketINotBetween(String value1, String value2) {
            addCriterion("socket_i not between", value1, value2, "socketI");
            return (Criteria) this;
        }

        public Criteria andSocketUIsNull() {
            addCriterion("socket_u is null");
            return (Criteria) this;
        }

        public Criteria andSocketUIsNotNull() {
            addCriterion("socket_u is not null");
            return (Criteria) this;
        }

        public Criteria andSocketUEqualTo(String value) {
            addCriterion("socket_u =", value, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketUNotEqualTo(String value) {
            addCriterion("socket_u <>", value, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketUGreaterThan(String value) {
            addCriterion("socket_u >", value, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketUGreaterThanOrEqualTo(String value) {
            addCriterion("socket_u >=", value, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketULessThan(String value) {
            addCriterion("socket_u <", value, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketULessThanOrEqualTo(String value) {
            addCriterion("socket_u <=", value, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketULike(String value) {
            addCriterion("socket_u like", value, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketUNotLike(String value) {
            addCriterion("socket_u not like", value, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketUIn(List<String> values) {
            addCriterion("socket_u in", values, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketUNotIn(List<String> values) {
            addCriterion("socket_u not in", values, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketUBetween(String value1, String value2) {
            addCriterion("socket_u between", value1, value2, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketUNotBetween(String value1, String value2) {
            addCriterion("socket_u not between", value1, value2, "socketU");
            return (Criteria) this;
        }

        public Criteria andSocketPIsNull() {
            addCriterion("socket_p is null");
            return (Criteria) this;
        }

        public Criteria andSocketPIsNotNull() {
            addCriterion("socket_p is not null");
            return (Criteria) this;
        }

        public Criteria andSocketPEqualTo(String value) {
            addCriterion("socket_p =", value, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPNotEqualTo(String value) {
            addCriterion("socket_p <>", value, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPGreaterThan(String value) {
            addCriterion("socket_p >", value, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPGreaterThanOrEqualTo(String value) {
            addCriterion("socket_p >=", value, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPLessThan(String value) {
            addCriterion("socket_p <", value, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPLessThanOrEqualTo(String value) {
            addCriterion("socket_p <=", value, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPLike(String value) {
            addCriterion("socket_p like", value, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPNotLike(String value) {
            addCriterion("socket_p not like", value, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPIn(List<String> values) {
            addCriterion("socket_p in", values, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPNotIn(List<String> values) {
            addCriterion("socket_p not in", values, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPBetween(String value1, String value2) {
            addCriterion("socket_p between", value1, value2, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketPNotBetween(String value1, String value2) {
            addCriterion("socket_p not between", value1, value2, "socketP");
            return (Criteria) this;
        }

        public Criteria andSocketStatusIsNull() {
            addCriterion("socket_status is null");
            return (Criteria) this;
        }

        public Criteria andSocketStatusIsNotNull() {
            addCriterion("socket_status is not null");
            return (Criteria) this;
        }

        public Criteria andSocketStatusEqualTo(String value) {
            addCriterion("socket_status =", value, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusNotEqualTo(String value) {
            addCriterion("socket_status <>", value, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusGreaterThan(String value) {
            addCriterion("socket_status >", value, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusGreaterThanOrEqualTo(String value) {
            addCriterion("socket_status >=", value, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusLessThan(String value) {
            addCriterion("socket_status <", value, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusLessThanOrEqualTo(String value) {
            addCriterion("socket_status <=", value, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusLike(String value) {
            addCriterion("socket_status like", value, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusNotLike(String value) {
            addCriterion("socket_status not like", value, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusIn(List<String> values) {
            addCriterion("socket_status in", values, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusNotIn(List<String> values) {
            addCriterion("socket_status not in", values, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusBetween(String value1, String value2) {
            addCriterion("socket_status between", value1, value2, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketStatusNotBetween(String value1, String value2) {
            addCriterion("socket_status not between", value1, value2, "socketStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusIsNull() {
            addCriterion("socket_clock_status is null");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusIsNotNull() {
            addCriterion("socket_clock_status is not null");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusEqualTo(String value) {
            addCriterion("socket_clock_status =", value, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusNotEqualTo(String value) {
            addCriterion("socket_clock_status <>", value, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusGreaterThan(String value) {
            addCriterion("socket_clock_status >", value, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusGreaterThanOrEqualTo(String value) {
            addCriterion("socket_clock_status >=", value, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusLessThan(String value) {
            addCriterion("socket_clock_status <", value, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusLessThanOrEqualTo(String value) {
            addCriterion("socket_clock_status <=", value, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusLike(String value) {
            addCriterion("socket_clock_status like", value, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusNotLike(String value) {
            addCriterion("socket_clock_status not like", value, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusIn(List<String> values) {
            addCriterion("socket_clock_status in", values, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusNotIn(List<String> values) {
            addCriterion("socket_clock_status not in", values, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusBetween(String value1, String value2) {
            addCriterion("socket_clock_status between", value1, value2, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andSocketClockStatusNotBetween(String value1, String value2) {
            addCriterion("socket_clock_status not between", value1, value2, "socketClockStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Integer value) {
            addCriterion("room_id =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Integer value) {
            addCriterion("room_id <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Integer value) {
            addCriterion("room_id >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_id >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Integer value) {
            addCriterion("room_id <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("room_id <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Integer> values) {
            addCriterion("room_id in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Integer> values) {
            addCriterion("room_id not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table socket_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table socket_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}