package com.fc.v2.iotmanage.model.respone;

import java.io.Serializable;
import java.util.Date;

public class SpaceInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_info.space_id
     *
     * @mbg.generated
     */
    private Integer spaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_info.space_id_v
     *
     * @mbg.generated
     */
    private String spaceIdV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_info.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_info.parent_id_v
     *
     * @mbg.generated
     */
    private String parentIdV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_info.space_name
     *
     * @mbg.generated
     */
    private String spaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_info.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column space_info.delete_flag
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table space_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_info.space_id
     *
     * @return the value of space_info.space_id
     *
     * @mbg.generated
     */
    public Integer getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_info.space_id
     *
     * @param spaceId the value for space_info.space_id
     *
     * @mbg.generated
     */
    public void setSpaceId(Integer spaceId) {
        this.spaceId = spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_info.space_id_v
     *
     * @return the value of space_info.space_id_v
     *
     * @mbg.generated
     */
    public String getSpaceIdV() {
        return spaceIdV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_info.space_id_v
     *
     * @param spaceIdV the value for space_info.space_id_v
     *
     * @mbg.generated
     */
    public void setSpaceIdV(String spaceIdV) {
        this.spaceIdV = spaceIdV == null ? null : spaceIdV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_info.parent_id
     *
     * @return the value of space_info.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_info.parent_id
     *
     * @param parentId the value for space_info.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_info.parent_id_v
     *
     * @return the value of space_info.parent_id_v
     *
     * @mbg.generated
     */
    public String getParentIdV() {
        return parentIdV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_info.parent_id_v
     *
     * @param parentIdV the value for space_info.parent_id_v
     *
     * @mbg.generated
     */
    public void setParentIdV(String parentIdV) {
        this.parentIdV = parentIdV == null ? null : parentIdV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_info.space_name
     *
     * @return the value of space_info.space_name
     *
     * @mbg.generated
     */
    public String getSpaceName() {
        return spaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_info.space_name
     *
     * @param spaceName the value for space_info.space_name
     *
     * @mbg.generated
     */
    public void setSpaceName(String spaceName) {
        this.spaceName = spaceName == null ? null : spaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_info.update_date
     *
     * @return the value of space_info.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_info.update_date
     *
     * @param updateDate the value for space_info.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column space_info.delete_flag
     *
     * @return the value of space_info.delete_flag
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column space_info.delete_flag
     *
     * @param deleteFlag the value for space_info.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }
}