package com.fc.v2.iotmanage.model.respone;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SpaceInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table space_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table space_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table space_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public SpaceInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table space_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpaceIdIsNull() {
            addCriterion("space_id is null");
            return (Criteria) this;
        }

        public Criteria andSpaceIdIsNotNull() {
            addCriterion("space_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceIdEqualTo(Integer value) {
            addCriterion("space_id =", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdNotEqualTo(Integer value) {
            addCriterion("space_id <>", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdGreaterThan(Integer value) {
            addCriterion("space_id >", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("space_id >=", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdLessThan(Integer value) {
            addCriterion("space_id <", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdLessThanOrEqualTo(Integer value) {
            addCriterion("space_id <=", value, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdIn(List<Integer> values) {
            addCriterion("space_id in", values, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdNotIn(List<Integer> values) {
            addCriterion("space_id not in", values, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdBetween(Integer value1, Integer value2) {
            addCriterion("space_id between", value1, value2, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("space_id not between", value1, value2, "spaceId");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVIsNull() {
            addCriterion("space_id_v is null");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVIsNotNull() {
            addCriterion("space_id_v is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVEqualTo(String value) {
            addCriterion("space_id_v =", value, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVNotEqualTo(String value) {
            addCriterion("space_id_v <>", value, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVGreaterThan(String value) {
            addCriterion("space_id_v >", value, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVGreaterThanOrEqualTo(String value) {
            addCriterion("space_id_v >=", value, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVLessThan(String value) {
            addCriterion("space_id_v <", value, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVLessThanOrEqualTo(String value) {
            addCriterion("space_id_v <=", value, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVLike(String value) {
            addCriterion("space_id_v like", value, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVNotLike(String value) {
            addCriterion("space_id_v not like", value, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVIn(List<String> values) {
            addCriterion("space_id_v in", values, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVNotIn(List<String> values) {
            addCriterion("space_id_v not in", values, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVBetween(String value1, String value2) {
            addCriterion("space_id_v between", value1, value2, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceIdVNotBetween(String value1, String value2) {
            addCriterion("space_id_v not between", value1, value2, "spaceIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Integer value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Integer value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Integer value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Integer value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Integer value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Integer> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Integer> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Integer value1, Integer value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdVIsNull() {
            addCriterion("parent_id_v is null");
            return (Criteria) this;
        }

        public Criteria andParentIdVIsNotNull() {
            addCriterion("parent_id_v is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdVEqualTo(String value) {
            addCriterion("parent_id_v =", value, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVNotEqualTo(String value) {
            addCriterion("parent_id_v <>", value, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVGreaterThan(String value) {
            addCriterion("parent_id_v >", value, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVGreaterThanOrEqualTo(String value) {
            addCriterion("parent_id_v >=", value, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVLessThan(String value) {
            addCriterion("parent_id_v <", value, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVLessThanOrEqualTo(String value) {
            addCriterion("parent_id_v <=", value, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVLike(String value) {
            addCriterion("parent_id_v like", value, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVNotLike(String value) {
            addCriterion("parent_id_v not like", value, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVIn(List<String> values) {
            addCriterion("parent_id_v in", values, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVNotIn(List<String> values) {
            addCriterion("parent_id_v not in", values, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVBetween(String value1, String value2) {
            addCriterion("parent_id_v between", value1, value2, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andParentIdVNotBetween(String value1, String value2) {
            addCriterion("parent_id_v not between", value1, value2, "parentIdV");
            return (Criteria) this;
        }

        public Criteria andSpaceNameIsNull() {
            addCriterion("space_name is null");
            return (Criteria) this;
        }

        public Criteria andSpaceNameIsNotNull() {
            addCriterion("space_name is not null");
            return (Criteria) this;
        }

        public Criteria andSpaceNameEqualTo(String value) {
            addCriterion("space_name =", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameNotEqualTo(String value) {
            addCriterion("space_name <>", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameGreaterThan(String value) {
            addCriterion("space_name >", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameGreaterThanOrEqualTo(String value) {
            addCriterion("space_name >=", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameLessThan(String value) {
            addCriterion("space_name <", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameLessThanOrEqualTo(String value) {
            addCriterion("space_name <=", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameLike(String value) {
            addCriterion("space_name like", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameNotLike(String value) {
            addCriterion("space_name not like", value, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameIn(List<String> values) {
            addCriterion("space_name in", values, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameNotIn(List<String> values) {
            addCriterion("space_name not in", values, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameBetween(String value1, String value2) {
            addCriterion("space_name between", value1, value2, "spaceName");
            return (Criteria) this;
        }

        public Criteria andSpaceNameNotBetween(String value1, String value2) {
            addCriterion("space_name not between", value1, value2, "spaceName");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(String value) {
            addCriterion("delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(String value) {
            addCriterion("delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(String value) {
            addCriterion("delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(String value) {
            addCriterion("delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(String value) {
            addCriterion("delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(String value) {
            addCriterion("delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLike(String value) {
            addCriterion("delete_flag like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotLike(String value) {
            addCriterion("delete_flag not like", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<String> values) {
            addCriterion("delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<String> values) {
            addCriterion("delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(String value1, String value2) {
            addCriterion("delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(String value1, String value2) {
            addCriterion("delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table space_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table space_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}