package com.fc.v2.iotmanage.model.respone;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SwitchInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public SwitchInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSwitchIdIsNull() {
            addCriterion("switch_id is null");
            return (Criteria) this;
        }

        public Criteria andSwitchIdIsNotNull() {
            addCriterion("switch_id is not null");
            return (Criteria) this;
        }

        public Criteria andSwitchIdEqualTo(Integer value) {
            addCriterion("switch_id =", value, "switchId");
            return (Criteria) this;
        }

        public Criteria andSwitchIdNotEqualTo(Integer value) {
            addCriterion("switch_id <>", value, "switchId");
            return (Criteria) this;
        }

        public Criteria andSwitchIdGreaterThan(Integer value) {
            addCriterion("switch_id >", value, "switchId");
            return (Criteria) this;
        }

        public Criteria andSwitchIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("switch_id >=", value, "switchId");
            return (Criteria) this;
        }

        public Criteria andSwitchIdLessThan(Integer value) {
            addCriterion("switch_id <", value, "switchId");
            return (Criteria) this;
        }

        public Criteria andSwitchIdLessThanOrEqualTo(Integer value) {
            addCriterion("switch_id <=", value, "switchId");
            return (Criteria) this;
        }

        public Criteria andSwitchIdIn(List<Integer> values) {
            addCriterion("switch_id in", values, "switchId");
            return (Criteria) this;
        }

        public Criteria andSwitchIdNotIn(List<Integer> values) {
            addCriterion("switch_id not in", values, "switchId");
            return (Criteria) this;
        }

        public Criteria andSwitchIdBetween(Integer value1, Integer value2) {
            addCriterion("switch_id between", value1, value2, "switchId");
            return (Criteria) this;
        }

        public Criteria andSwitchIdNotBetween(Integer value1, Integer value2) {
            addCriterion("switch_id not between", value1, value2, "switchId");
            return (Criteria) this;
        }

        public Criteria andSwitchNameIsNull() {
            addCriterion("switch_name is null");
            return (Criteria) this;
        }

        public Criteria andSwitchNameIsNotNull() {
            addCriterion("switch_name is not null");
            return (Criteria) this;
        }

        public Criteria andSwitchNameEqualTo(String value) {
            addCriterion("switch_name =", value, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameNotEqualTo(String value) {
            addCriterion("switch_name <>", value, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameGreaterThan(String value) {
            addCriterion("switch_name >", value, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameGreaterThanOrEqualTo(String value) {
            addCriterion("switch_name >=", value, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameLessThan(String value) {
            addCriterion("switch_name <", value, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameLessThanOrEqualTo(String value) {
            addCriterion("switch_name <=", value, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameLike(String value) {
            addCriterion("switch_name like", value, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameNotLike(String value) {
            addCriterion("switch_name not like", value, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameIn(List<String> values) {
            addCriterion("switch_name in", values, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameNotIn(List<String> values) {
            addCriterion("switch_name not in", values, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameBetween(String value1, String value2) {
            addCriterion("switch_name between", value1, value2, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchNameNotBetween(String value1, String value2) {
            addCriterion("switch_name not between", value1, value2, "switchName");
            return (Criteria) this;
        }

        public Criteria andSwitchOneIsNull() {
            addCriterion("switch_one is null");
            return (Criteria) this;
        }

        public Criteria andSwitchOneIsNotNull() {
            addCriterion("switch_one is not null");
            return (Criteria) this;
        }

        public Criteria andSwitchOneEqualTo(String value) {
            addCriterion("switch_one =", value, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneNotEqualTo(String value) {
            addCriterion("switch_one <>", value, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneGreaterThan(String value) {
            addCriterion("switch_one >", value, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneGreaterThanOrEqualTo(String value) {
            addCriterion("switch_one >=", value, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneLessThan(String value) {
            addCriterion("switch_one <", value, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneLessThanOrEqualTo(String value) {
            addCriterion("switch_one <=", value, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneLike(String value) {
            addCriterion("switch_one like", value, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneNotLike(String value) {
            addCriterion("switch_one not like", value, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneIn(List<String> values) {
            addCriterion("switch_one in", values, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneNotIn(List<String> values) {
            addCriterion("switch_one not in", values, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneBetween(String value1, String value2) {
            addCriterion("switch_one between", value1, value2, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchOneNotBetween(String value1, String value2) {
            addCriterion("switch_one not between", value1, value2, "switchOne");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoIsNull() {
            addCriterion("switch_two is null");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoIsNotNull() {
            addCriterion("switch_two is not null");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoEqualTo(String value) {
            addCriterion("switch_two =", value, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoNotEqualTo(String value) {
            addCriterion("switch_two <>", value, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoGreaterThan(String value) {
            addCriterion("switch_two >", value, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoGreaterThanOrEqualTo(String value) {
            addCriterion("switch_two >=", value, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoLessThan(String value) {
            addCriterion("switch_two <", value, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoLessThanOrEqualTo(String value) {
            addCriterion("switch_two <=", value, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoLike(String value) {
            addCriterion("switch_two like", value, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoNotLike(String value) {
            addCriterion("switch_two not like", value, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoIn(List<String> values) {
            addCriterion("switch_two in", values, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoNotIn(List<String> values) {
            addCriterion("switch_two not in", values, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoBetween(String value1, String value2) {
            addCriterion("switch_two between", value1, value2, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchTwoNotBetween(String value1, String value2) {
            addCriterion("switch_two not between", value1, value2, "switchTwo");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeIsNull() {
            addCriterion("switch_three is null");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeIsNotNull() {
            addCriterion("switch_three is not null");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeEqualTo(String value) {
            addCriterion("switch_three =", value, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeNotEqualTo(String value) {
            addCriterion("switch_three <>", value, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeGreaterThan(String value) {
            addCriterion("switch_three >", value, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeGreaterThanOrEqualTo(String value) {
            addCriterion("switch_three >=", value, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeLessThan(String value) {
            addCriterion("switch_three <", value, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeLessThanOrEqualTo(String value) {
            addCriterion("switch_three <=", value, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeLike(String value) {
            addCriterion("switch_three like", value, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeNotLike(String value) {
            addCriterion("switch_three not like", value, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeIn(List<String> values) {
            addCriterion("switch_three in", values, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeNotIn(List<String> values) {
            addCriterion("switch_three not in", values, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeBetween(String value1, String value2) {
            addCriterion("switch_three between", value1, value2, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchThreeNotBetween(String value1, String value2) {
            addCriterion("switch_three not between", value1, value2, "switchThree");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusIsNull() {
            addCriterion("switch_status is null");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusIsNotNull() {
            addCriterion("switch_status is not null");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusEqualTo(String value) {
            addCriterion("switch_status =", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusNotEqualTo(String value) {
            addCriterion("switch_status <>", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusGreaterThan(String value) {
            addCriterion("switch_status >", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusGreaterThanOrEqualTo(String value) {
            addCriterion("switch_status >=", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusLessThan(String value) {
            addCriterion("switch_status <", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusLessThanOrEqualTo(String value) {
            addCriterion("switch_status <=", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusLike(String value) {
            addCriterion("switch_status like", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusNotLike(String value) {
            addCriterion("switch_status not like", value, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusIn(List<String> values) {
            addCriterion("switch_status in", values, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusNotIn(List<String> values) {
            addCriterion("switch_status not in", values, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusBetween(String value1, String value2) {
            addCriterion("switch_status between", value1, value2, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andSwitchStatusNotBetween(String value1, String value2) {
            addCriterion("switch_status not between", value1, value2, "switchStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNull() {
            addCriterion("room_id is null");
            return (Criteria) this;
        }

        public Criteria andRoomIdIsNotNull() {
            addCriterion("room_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoomIdEqualTo(Integer value) {
            addCriterion("room_id =", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotEqualTo(Integer value) {
            addCriterion("room_id <>", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThan(Integer value) {
            addCriterion("room_id >", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("room_id >=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThan(Integer value) {
            addCriterion("room_id <", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdLessThanOrEqualTo(Integer value) {
            addCriterion("room_id <=", value, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdIn(List<Integer> values) {
            addCriterion("room_id in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotIn(List<Integer> values) {
            addCriterion("room_id not in", values, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdBetween(Integer value1, Integer value2) {
            addCriterion("room_id between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andRoomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("room_id not between", value1, value2, "roomId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table switch_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}