package com.fc.v2.iotmanage.model.respone;

import java.io.Serializable;
import java.util.Date;

public class SwitchInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_info.switch_id
     *
     * @mbg.generated
     */
    private Integer switchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_info.switch_name
     *
     * @mbg.generated
     */
    private String switchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_info.switch_one
     *
     * @mbg.generated
     */
    private String switchOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_info.switch_two
     *
     * @mbg.generated
     */
    private String switchTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_info.switch_three
     *
     * @mbg.generated
     */
    private String switchThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_info.switch_status
     *
     * @mbg.generated
     */
    private String switchStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_info.room_id
     *
     * @mbg.generated
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column switch_info.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table switch_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_info.id
     *
     * @return the value of switch_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_info.id
     *
     * @param id the value for switch_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_info.switch_id
     *
     * @return the value of switch_info.switch_id
     *
     * @mbg.generated
     */
    public Integer getSwitchId() {
        return switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_info.switch_id
     *
     * @param switchId the value for switch_info.switch_id
     *
     * @mbg.generated
     */
    public void setSwitchId(Integer switchId) {
        this.switchId = switchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_info.switch_name
     *
     * @return the value of switch_info.switch_name
     *
     * @mbg.generated
     */
    public String getSwitchName() {
        return switchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_info.switch_name
     *
     * @param switchName the value for switch_info.switch_name
     *
     * @mbg.generated
     */
    public void setSwitchName(String switchName) {
        this.switchName = switchName == null ? null : switchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_info.switch_one
     *
     * @return the value of switch_info.switch_one
     *
     * @mbg.generated
     */
    public String getSwitchOne() {
        return switchOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_info.switch_one
     *
     * @param switchOne the value for switch_info.switch_one
     *
     * @mbg.generated
     */
    public void setSwitchOne(String switchOne) {
        this.switchOne = switchOne == null ? null : switchOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_info.switch_two
     *
     * @return the value of switch_info.switch_two
     *
     * @mbg.generated
     */
    public String getSwitchTwo() {
        return switchTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_info.switch_two
     *
     * @param switchTwo the value for switch_info.switch_two
     *
     * @mbg.generated
     */
    public void setSwitchTwo(String switchTwo) {
        this.switchTwo = switchTwo == null ? null : switchTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_info.switch_three
     *
     * @return the value of switch_info.switch_three
     *
     * @mbg.generated
     */
    public String getSwitchThree() {
        return switchThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_info.switch_three
     *
     * @param switchThree the value for switch_info.switch_three
     *
     * @mbg.generated
     */
    public void setSwitchThree(String switchThree) {
        this.switchThree = switchThree == null ? null : switchThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_info.switch_status
     *
     * @return the value of switch_info.switch_status
     *
     * @mbg.generated
     */
    public String getSwitchStatus() {
        return switchStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_info.switch_status
     *
     * @param switchStatus the value for switch_info.switch_status
     *
     * @mbg.generated
     */
    public void setSwitchStatus(String switchStatus) {
        this.switchStatus = switchStatus == null ? null : switchStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_info.create_time
     *
     * @return the value of switch_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_info.create_time
     *
     * @param createTime the value for switch_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_info.room_id
     *
     * @return the value of switch_info.room_id
     *
     * @mbg.generated
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_info.room_id
     *
     * @param roomId the value for switch_info.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column switch_info.type
     *
     * @return the value of switch_info.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column switch_info.type
     *
     * @param type the value for switch_info.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}